<!-- Bootstrap core JavaScript -->
<script src="{{ asset('script/navbar-scroll.js') }}"></script>
<script src="{{ asset('ap/vendors/js/vendor.bundle.base.js') }}"></script>
<script src="{{ asset('ap/vendors/chart.js/Chart.min.js') }}"></script>
<script src="{{ asset('ap/vendors/datatables.net/jquery.dataTables.js') }}"></script>
<script src="{{ asset('ap/vendors/datatables.net-bs4/dataTables.bootstrap4.js') }}"></script>
<script src="{{ asset('ap/js/dataTables.select.min.js') }}"></script>
<script src="{{ asset('ap/js/off-canvas.js') }}"></script>
<script src="{{ asset('ap/js/hoverable-collapse.js') }}"></script>
<script src="{{ asset('ap/js/template.js') }}"></script>
<script src="{{ asset('ap/js/settings.js') }}"></script>
<script src="{{ asset('ap/js/todolist.js') }}"></script>
<script src="{{ asset('ap/js/dashboard.js') }}"></script>
<script src="{{ asset('ap/js/Chart.roundedBarCharts.js') }}"></script>
<script src="//cdn.ckeditor.com/4.14.1/standard/ckeditor.js"></script>
<script src="{{ asset('plugins/jquery/jquery.min.js') }}"></script>
<script src="{{ asset('plugins/jquery-ui/jquery-ui.min.js') }}"></script>
<script src="{{ asset('ap/js/select2.js') }}"></script>
<script src="{{asset('ap/vendors/select2/select2.min.js')}}"></script>